name: Start Python Server (v2)

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  start-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Start server from v2
        working-directory: ./v2
        run: |
          echo "Starting server..."
          echo "Serving folder: $(pwd)"

          python -m http.server 8000 &
          sleep 5

      - name: Test server
        run: |
          curl http://localhost:8000
